### ISSUE TITLE
Split on accentuated characters

### ISSUE THREAD

**Issue by patrickdrouin** [keredson/wordninja#24]
Hello,

I ran into problem splitting on accentuated characters. I built a large dictionary file and this is the behaviour I get : 

lm.split('Jenesaispasquoienpenserdecemachinlàmaisçasemblefonctionner')
['Je', 'ne', 'sais', 'pas', 'quoi', 'en', 'penser', 'de', 'ce', 'machin', 'l', 'mais', 'as', 'emble', 'fonctionner']

Expected output would be : 
['Je', 'ne', 'sais', 'pas', 'quoi', 'en', 'penser', 'de', 'ce', 'machin', 'là', 'mais', 'ça', 'semble', 'fonctionner']

The à and ç characters seem to be causing the problems here. 
Any pointers for me?

**Comment by kuranai** [comment]
Hi @patrickdrouin,
you can fix this, when you change the code like in the following pull request:
https://github.com/keredson/wordninja/pull/13/files

I have tested your string with this fix because I was searching for the same.
Result is like your expected:
['Je', 'ne', 'sais', 'pas', 'quoi', 'en', 'penser', 'de', 'ce', 'machin', 'là', 'mais', 'ça', 'semble', 'fonctionner']

I have used the following fr_50k.txt wordlist from here for testing:
https://github.com/hermitdave/FrequencyWords/tree/master/content/2018/fr

Hope that helps.

**Comment by patrickdrouin** [comment]
@kuranai Thanks, it did help quite a bit the the fr_50k is an interesting resource.
